name: Lint

on: pull_request

jobs:
    lint-charm:
        name: "Run linter"
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: '3.x'
                  architecture: 'x64'
            - name: "Install flake8 and flake8-docstrings"
              run: |
                  pip install -r requirements-dev.txt

            - name: "lint the charms"
              run: |
                  make lint

    build-charm:
        name: "Build the charms"
        needs: lint-charm
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup operator environment
              uses: charmed-kubernetes/actions-operator@main
              with:
                provider: lxd
                juju-channel: 3.1/stable
            - name: "Build the charms"
              shell: bash
              run: |
                  make charm
                  echo "charm version: $(cat version)"
